<a href="https://colab.research.google.com/github/NavJyo/NLP/blob/main/Intro_to_Stemming%2CLemmatization_and_Wrod_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk

In [ ]:
pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
paragraph = "Thank you. Thank you. So, my father used to always tell me something which I want to share with you, that why do you want to fit inside a glass slipper? You know, like we were told, like Cinderella did, why do you want to fit inside a glass slipper when you can shatter the glass ceiling? I want to tell you a little secret. I’m not very fond of this phrase, breaking the glass ceiling. Why does it annoy me? Because it takes the context of everything that I have done. All my achievements, all my hard work and puts it into a box as if my ambition was that I want to find a glass ceiling and break it. Not at all. To be really honest, I was never on a mission to break, to shatter anything."

In [ ]:
sentences = nltk.sent_tokenize(paragraph)

In [ ]:
words = nltk.word_tokenize(paragraph)

In [ ]:
from nltk.corpus import stopwords 

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
stemmer = PorterStemmer()

In [ ]:
for i in range(len(sentences)): 
  words = nltk.word_tokenize(sentences[i]) 
  words = [stemmer.stem(i) for i in words  if i not  in set(stopwords.words('english'))] 
  sentences[i] = ' '.join(words)

In [ ]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.stem import WordNetLemmatizer 

In [ ]:
for i in range(len(sentences)):
  lem = WordNetLemmatizer()  
  words = nltk.word_tokenize(sentences[i])
  words = [lem.lemmatize(i) for i in words if i not in set(stopwords.words('english'))] 
  sentences[i] = ' '.join(words)



In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
ps = PorterStemmer()

In [ ]:
from nltk.stem import WordNetLemmatizer 

In [ ]:

from nltk.corpus import stopwords

In [ ]:
sentences = nltk.sent_tokenize(paragraph)

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
corpus = []

In [ ]:
for i in range(len(sentences)):
  review = re.sub('[a-zA-Z]',' ', sentences[i]) 
  review = review.lower() 
  review = review.split() 
  review = [ps.stem(word) for word in review if review not in set(stopwords.words('english'))] 
  review = ' '.join(review) 
  corpus.append(review) 

TypeError: ignored

In [8]:
from tensorflow.keras.preprocessing.text import one_hot

In [9]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',] 

In [10]:
voc_size = 1000

In [13]:
one_hot_repr = [one_hot(word,voc_size) for word in sent]

In [14]:
from tensorflow.keras.layers import Embedding

In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [18]:
from tensorflow.keras.models import Sequential

In [19]:
import numpy as np

In [20]:
sent_length = 8

In [21]:
embedded_docs = pad_sequences(one_hot_repr,maxlen=sent_length,padding='pre') 
print(embedded_docs)

[[  0   0   0   0 153 203 988 323]
 [  0   0   0   0 153 203 988 316]
 [  0   0   0   0 153 551 988 211]
 [  0   0   0 926 210 688 957 556]
 [  0   0   0 926 210 688 957 794]
 [  0   0   0 782 153 320 988  50]
 [  0   0   0   0 837 271 909 957]]


In [22]:
dim = 10

In [23]:
model = Sequential()

In [24]:
from IPython.terminal.embed import EmbeddedMagics
model.add(Embedding(voc_size,10,input_length=sent_length)) 
model.compile('adam','mse') 

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             10000     
                                                                 
Total params: 10,000
Trainable params: 10,000
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 103ms/step


array([[-0.01471491,  0.01653894, -0.02360064,  0.00900419, -0.01584036,
        -0.03540658,  0.01151928, -0.01704044, -0.03032874,  0.03547709],
       [-0.01471491,  0.01653894, -0.02360064,  0.00900419, -0.01584036,
        -0.03540658,  0.01151928, -0.01704044, -0.03032874,  0.03547709],
       [-0.01471491,  0.01653894, -0.02360064,  0.00900419, -0.01584036,
        -0.03540658,  0.01151928, -0.01704044, -0.03032874,  0.03547709],
       [-0.01471491,  0.01653894, -0.02360064,  0.00900419, -0.01584036,
        -0.03540658,  0.01151928, -0.01704044, -0.03032874,  0.03547709],
       [-0.0091634 ,  0.04090326, -0.00153679,  0.04863167,  0.02015375,
         0.00264297, -0.01949446,  0.04965705, -0.0277359 ,  0.03088481],
       [ 0.04863992,  0.04420101, -0.0087317 , -0.03195275,  0.04985661,
         0.04759779,  0.03716029,  0.04801876, -0.02071533, -0.04338942],
       [-0.0207456 , -0.04901632, -0.01927872,  0.04862991,  0.02319653,
        -0.02036747,  0.00534992, -0.01885374